# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: tensorflow
  version: 2.10.1

about:
  home: https://tensorflow.org
  license: Apache License
  summary: 'TensorFlow conda package based on the PyPI wheels.

  For GPU support, install cudatoolkit 11.3.1 and cudnn 8.2.1 which are available as conda packages on the default channel.'

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python=3.7
    - pip
    # - conda-forge::numpy=1.19.5
    # - conda-forge::h5py=3.1.0
    # - conda-forge::scipy=1.7.3

  run:
    - python=3.7
    - pip
    # - conda-forge::numpy~=1.19.5
    # - conda-forge::h5py~=3.1.0
    # - conda-forge::scipy>=1.4.1,<=1.7.3

test:
  imports:
    - tensorflow