# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: tensorflow
  version: 2.7.4

about:
  home: https://tensorflow.org
  license: Apache License
  summary: 'TensorFlow conda package based on the PyPI wheels.

  For GPU support, install cudatoolkit 11.3.1 and cudnn 8.2.1 which are available as conda packages on the default channel.'

build:
  number: 1

source:
  path: ../

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python=3.7
    - numpy
    - h5py
    - pip

  run:
    - python=3.7
    - numpy
    - h5py
    - pip

test:
  imports:
    - tensorflow