# Ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: tensorflow
  version: 2.7.0

about:
  home: https://tensorflow.org
  license: Apache License
  summary: 'TensorFlow 2.7.0 conda package based on the PyPI wheels.

  Also includes numpy 1.18.1, h5py 3.10 and opencv-python-headless 4.2.0.34.

  For GPU support, install cudatoolkit 11.3.1 and cudnn 8.2.1 which are available as conda packages on the default channel.'

build:
  number: 2.7.0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'

  host:
    - python=3.7
    - pip

  run:
    - python=3.7
    - pip

test:
  imports:
    - tensorflow
    - numpy
    - h5py
    - cv2