name: build_tensorflow

dependencies:
- python=3.7
- conda-build
- anaconda-client
- conda-verify
- conda-forge::numpy=1.21.5
- conda-forge::pyside2=5.13.2
- conda-forge::h5py=3.6.0
- conda-forge::scipy=1.7.3
- pip
- pip:
    - "--requirement=./requirements.tensorflow.txt"